### PR TITLE
Add Scala 2.13 and Scala.js 1.x support

### PR DESCRIPTION
**Pull request by exoego**
Support matrix |Scala.js 0.6|Scala.js 1.x
---|---|---
Scala 2.13 | ✔️ | ✔️
Scala 2.12 | ✔️ | ✔️
Scala 2.11 | ✔️ | ❌ 

Scala 2.11 is dropped for Scala.js 1.x.
This is because `utest` does not support Scala.js 1.x with Scala 2.11.

Many errors/warnings for Scala 2.13 and Scala.js 1.x are adressed.

### CODE REVIEW

**Comment by rpiaggio** [comment]
Thank you so much @exoego for all this work!

Unfortunately, this repo is not being maintained anymore, and I don't even have permissions to merge the PR. Please feel free to publish your fork.

Also for `java.time` support in Scala.js may I recommend taking a look at https://github.com/cquiroz/scala-java-time ?

**Comment by hautbrion** [comment]
(@rpiaggio You're an owner of the repo now.)
(@exoego merged!)

**Comment by rpiaggio** [comment]
@hautbrion Thank you very much!

Let me attempt to do a release then.

**Comment by rpiaggio** [comment]
Version `1.2.0` is released with these changes. Sorry for the delay.

**Pull request merged**
