### PR TITLE
Fix some method signature

### PR DESCRIPTION
**Pull request by ant8e**

### CODE REVIEW

**Comment by rpiaggio** [comment]
Thank you for catching this @ant8e ! It seems I carried those signatures over from the `jsjoda` facade, where I tried to define those parameters as `Double`s because of [this](http://stackoverflow.com/questions/27821841/working-with-opaque-types-char-and-long).

They should definitely be `Long`s here, to correctly implement the `java.time` API.

**Comment by ant8e** [comment]
I found out only because I needed to call one these methods.  So pure luck indeed. 
When I saw those Double, that exactly what I thought might have happened. It must have been quite boring to implement all these methods, not surprising that you missed a couple.

So, by the way any plan to do a new release ?

**Comment by rpiaggio** [comment]
I'm currently integrating timezone support and was planning to release `1.1.0` when that is ready. If I see that takes too long (it shouldn't), I will release a `1.0.8` to include this PR.

**Comment by ant8e** [comment]
On another topic, jsjoda does not support yet formatting that depends on the Locale. I need this for one of my use case. Did you by chance have dealt with this in the past and could you offer a suggestion ? I started looking into https://github.com/cquiroz/scala-java-locales not sure yet that it can offer a solution.

**Comment by rpiaggio** [comment]
I have just released version `1.1.0` which includes this PR and provides support for timezones.

As for locale formatting: `scala-java-locales` definitely provides the necessary functionality but I'm afraid it would require a bit of work to adapt, implementing the necessary methods that are based on locale either on `js-joda` or on the facade.

Until `js-joda` provides support for locales though and since we only need English language support, for the moment we are making do with things like:

```scala
  implicit class LocalDateClientOps(ld: LocalDate) {
    def formatFull: String = s"${ld.getMonth.toString.toLowerCase.capitalize} ${ld.getDayOfMonth}, ${ld.getYear}"
  }
```

**Comment by ant8e** [comment]
Thanks for your fast release.

I have managed to have some success with `scala-java-locales`  to get the Weekdays localized name

```scala
implicit class DayOfWeekOps(day: DayOfWeek) {
    def displayShortName = {
      val isoDays = {
        val jvmDays = java.text.DateFormatSymbols.getInstance().getShortWeekdays.toList.drop(1) // position 0 is empty, then SUNDAY, MONDAY ....
        jvmDays.drop(1) ++ jvmDays.take(1) // Put MONDAY first, SUNDAY last as in ISO-8601
      }
      isoDays(day.getValue - 1) // MONDAY is weirdly at index 1 in ISO-8601
    }
  }
```

**Comment by rpiaggio** [comment]
You are most welcome.

Glad to hear you made `scala-java-locales` work for formatting. Thank you for the code.

**Comment by rpiaggio** [comment]
@ant8e You may want to take a look at https://github.com/cquiroz/scala-java-time. I just discovered it implements the java-time API with locales.

**Comment by ant8e** [comment]
@rpiaggio nice discovery. Will definitely take a look at i when time permits.

**Pull request merged**
